### ISSUE TITLE
検索履歴が存在しないとエラーになる

### ISSUE THREAD

**Issue by thinca** [osyo-manga/vim-anzu#15]
```
$ vim -i NONE
```

![](http://i.gyazo.com/5e60dcc6673524e69e45cf3487a2b7da.png)

`@/` が空の場合に発生するようです。

**Comment by osyo-manga** [comment]
ありがとうございます。とりあえず、エラーにならないように対応しました。

**Comment by thinca** [comment]
ありがとうございます！エラー出なくなったのを確認しました！
