### ISSUE TITLE
Could you provide a more detailed manual in English?

### ISSUE THREAD

**Issue by jackywu** [osyo-manga/vim-anzu#16]
At first, I like your anzu plugin very much. But I can not dive in deep anymore.
Could you provide a more detailed manual in English?

what's more, could you tell me how can I make the search result like this https://camo.githubusercontent.com/ae41f5093595963fb55f63d4209a8a384210c601/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3231343438382f313530363531342f32356463313437632d343933302d313165332d393738302d6138316338616537653038372e676966: anzu(13/23) on screen ?

**Comment by osyo-manga** [comment]
Sorry, I can't English :(

> what's more, could you tell me how can I make the search result like this

Please setting,

```vim
nmap n <Plug>(anzu-mode-n)
nmap N <Plug>(anzu-mode-N)
```

anzu-mode is `anzu(13/42)` in screen.

**Comment by jackywu** [comment]
thanks for reply. I mean that in edit area. please see the picture in
attachment.

====================

*with best regards,*

Jacky Wu

*jacky.wucheng@gmail.com <jacky.wucheng@gmail.com>*

weibo: @object

====================

2015-05-12 9:43 GMT+08:00 osyo-manga <notifications@github.com>:

**Comment by osyo-manga** [comment]
I don't see the picture.

**Comment by jackywu** [comment]
what's your e-mail?  may I send the picture to your e-mail?

====================

*with best regards,*

Jacky Wu

*jacky.wucheng@gmail.com <jacky.wucheng@gmail.com>*

weibo: @object

====================

2015-05-12 9:57 GMT+08:00 osyo-manga <notifications@github.com>:

**Comment by jackywu** [comment]
I paste the picture here <http://ctrlv.in/573689>

====================

*with best regards,*

Jacky Wu

*jacky.wucheng@gmail.com <jacky.wucheng@gmail.com>*

weibo: @object

====================

2015-05-12 9:57 GMT+08:00 osyo-manga <notifications@github.com>:

**Comment by osyo-manga** [comment]
OK, I see.
Thanks :)

**Comment by osyo-manga** [comment]
Please setting,

```vim
nmap n <Plug>(anzu-mode-n)
nmap N <Plug>(anzu-mode-N)
```

and input key `n`(or `N`) after search.

**Comment by jackywu** [comment]
I get it. thanks a lot.

====================

*with best regards,*

Jacky Wu

*jacky.wucheng@gmail.com <jacky.wucheng@gmail.com>*

weibo: @object

====================

2015-05-12 12:25 GMT+08:00 osyo-manga <notifications@github.com>:
