### ISSUE TITLE
`gd` to go to definition (like * search) does not update search term

### ISSUE THREAD

**Issue by davidosomething** [osyo-manga/vim-anzu#18]
When on:

```
let g:anzu_enable_CursorMoved_AnzuUpdateSearchStatus = 1
```

Using  `gd` on a variable or function shows `anzu(#/#)` instead of `variablename(#/#)` 

How can I set it?

**Comment by osyo-manga** [comment]
hmm...
Please tell me steps to reproduce.

**Comment by davidosomething** [comment]
Here is test file:

```viml
" vimrc
Plug 'osyo-manga/vim-anzu'
let g:anzu_enable_CursorMoved_AnzuUpdateSearchStatus = 1
nmap n <Plug>(anzu-n-with-echo)
```

```javascript
// test.js
var xyz = 1;
xyz = 2;
xyz = 3;
console.log(xyz);
```

on line `console.log(xyz)` put cursor on `y` and press normal mode `gd` (vim builtin, see `:h gd`)
press `n` to go to next result, see anzu status as `anzu(#/#)`


maybe i won't use `gd` anymore and just use `*`. It seems to be unreliable.

**Comment by osyo-manga** [comment]
Thanks.
I fixed it. Please update plugin.

**Comment by davidosomething** [comment]
thank you! it is working :)

**Comment by osyo-manga** [comment]
OK, Thanks :)
