### ISSUE TITLE
[[ and ]] (jump to function block) causes anzu echo

### ISSUE THREAD

**Issue by davidosomething** [osyo-manga/vim-anzu#19]
`[[` and `]]` (jump to function block) causes anzu echo in normal mode

**Comment by davidosomething** [comment]
i have `  let g:anzu_enable_CursorMoved_AnzuUpdateSearchStatus = 1`

**Comment by davidosomething** [comment]
`:verb nmap [[`

is from default php runtime:

```
n  [[          *@?\(.*\%#\)\@!\_^\s*\zs\(\(abstract\s\+\|final\s\+\|private\s\+\|protected\s\+\|public\s\+\|static\s\+\)*function\|\(abstract\s\+\|final\s\+\)*class\|interface\)?<CR>:nohls<CR>
        Last set from /usr/local/Cellar/neovim/0.1.2/share/nvim/runtime/ftplugin/php.vim
```

**Comment by PezCoder** [comment]
It causes anzu echo + the whole bottom bar on powerline fills with the long search character. It should have some max-length, looks ugly.
<img width="1278" alt="screen shot 2016-11-12 at 12 27 55 pm" src="https://cloud.githubusercontent.com/assets/8057916/20236216/7848beb2-a8d3-11e6-925d-310210da6977.png">

**Comment by davidosomething** [comment]
btw cause is that `[[` is a recursive mapping to `*` (which triggers anzu), so you could temporarily unmap `*` before running `[[` and then remap it afterwards
it will be a little annoying since you will need to map `[[` to call a custom function that unmaps, runs `normal *@?\(.*\%#\)\@!\_^\s*\zs\(\(abstract\s\+\|final\s\+\|private\s\+\|protected\s\+\|public\s\+\|static\s\+\)*function\|\(abstract\s\+\|final\s\+\)*class\|interface\)?<CR>:nohls<CR>` and then remap to whatever it was before

**Comment by PezCoder** [comment]
@davidosomething That looks way complex for me & it'll fill up the vimrc with hacks that i don't want to put. I'll rather live with it until the fix comes.

**Comment by PezCoder** [comment]
@osyo-manga Can you help us in the above issue ?

**Comment by osyo-manga** [comment]
hi, Thank for issues. Sorry for the late reply.
I do not understand what is wrong.

**Comment by PezCoder** [comment]
@osyo-manga Please check the above mentioned screenshot. Anzu is covering the whole airline, nothing is visible.

**Comment by 0xBADDCAFE** [comment]
@PezCoder You should understand @davidosomething 's reply. In php default ftplugin, <kbd>[[</kbd> map contains <kbd>*</kbd>. So anzu.vim echoes search results when fire `CursorMoved` autocmd if `let g:anzu_enable_CursorMoved_AnzuUpdateSearchStatus = 1` is set (like in your current [.vimrc](https://github.com/PezCoder/dotfiles/blob/master/vimrc#L165)). It only causes in php filetype, and cause is hack of <kbd>[[</kbd> mapping in ftplugin/php.vim rather than anzu.vim.

@davidosomething Closeable? Do you hope any feature?

**Comment by PezCoder** [comment]
@0xBADDCAFE Understood !

**Comment by davidosomething** [comment]
problem is with php.vim overriding native `[[`, so closing issue

**Comment by osyo-manga** [comment]
@0xBADDCAFE Thank you!!
