### ISSUE TITLE
anzu only shows 1000 matches maximum

### ISSUE THREAD

**Issue by pmcRTR** [osyo-manga/vim-anzu#20]
When I search for a string that has more than 1000 matches, anzu only reports the current match as being match number X out of 1000 matches found.

**Comment by osyo-manga** [comment]
hi.
Please setting `g:anzu_search_limit`.

**Comment by pmcRTR** [comment]
Worked like a charm - thank you! :)

**Comment by osyo-manga** [comment]
:)
